### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Hillernz** [Hillernz/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Dimatom00** [comment]
I'm Dmitry Gordon. I am a well-known Ukrainian journalist. I have interviewed more than 1,000 people in my life. I like to do interviews. I want to do my interviews better. I think that interviewing is extremely important.

**Comment by Hillernz** [comment]
I'm Dmitry Gordon. I am a well-known Ukrainian journalist. I have interviewed more than 1,000 people in my life. I like to do interviews. I want to do my interviews better. I think that interviewing is extremely important.
